# Generated by Django 5.2.10 on 2026-03-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_nomination_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoting',
            name='voting_type',
            field=models.CharField(choices=[('public', 'Публичное'), ('private', 'Закрытое')], default='public', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('public', 'Публичное'), ('private', 'Закрытое')], default='public', max_length=10, verbose_name='Тип'),
        ),
    ]
