# Generated by Django 5.2.10 on 2026-03-26 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_historicalvoting_voting_type_voting_voting_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoting',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='voting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_votings', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.CreateModel(
            name='VotingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting')),
            ],
            options={
                'verbose_name': 'Участие в голосовании',
                'verbose_name_plural': 'Участия в голосованиях',
                'unique_together': {('user', 'voting')},
            },
        ),
        migrations.AddField(
            model_name='voting',
            name='participants_users',
            field=models.ManyToManyField(related_name='joined_votings', through='voting.VotingParticipation', to=settings.AUTH_USER_MODEL, verbose_name='Участники-пользователи'),
        ),
    ]
