# Generated by Django 5.2.10 on 2026-03-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_historicalvoting_owner_voting_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoting',
            name='rules_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Файл с правилами'),
        ),
        migrations.AddField(
            model_name='voting',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='rules/%Y/%m/', verbose_name='Файл с правилами'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='participants/%Y/%m/', verbose_name='Аватар'),
        ),
    ]
