# Generated by Django 5.2.10 on 2026-03-26 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_historicalvoting_rules_file_voting_rules_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnomination',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical nomination', 'verbose_name_plural': 'historical nominations'},
        ),
        migrations.AlterModelOptions(
            name='historicalparticipant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical participant', 'verbose_name_plural': 'historical participants'},
        ),
        migrations.AlterModelOptions(
            name='historicalvote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vote', 'verbose_name_plural': 'historical votes'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='votingparticipation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalvoting',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='voting',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='historicalnomination',
            name='voting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.voting'),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='nomination',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.nomination'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='participant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.participant'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='voted_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='voting.voting'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='voting.nomination'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.participant'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
