# Generated by Django 5.2.10 on 2026-03-26 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_historicalnomination_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnomination',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Номинация', 'verbose_name_plural': 'historical Номинации'},
        ),
        migrations.AlterModelOptions(
            name='historicalparticipant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Участник', 'verbose_name_plural': 'historical Участники'},
        ),
        migrations.AlterModelOptions(
            name='historicalvote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Голос', 'verbose_name_plural': 'historical Голоса'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name': 'Номинация', 'verbose_name_plural': 'Номинации'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterModelOptions(
            name='votingparticipation',
            options={'verbose_name': 'Участие в голосовании', 'verbose_name_plural': 'Участия в голосованиях'},
        ),
        migrations.AlterField(
            model_name='historicalnomination',
            name='voting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.voting', verbose_name='Голосование'),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='nomination',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.nomination', verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='participant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.participant', verbose_name='За кого голос'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='voted_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='voting.voting', verbose_name='Голосование'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='voting.nomination', verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.participant', verbose_name='За кого голос'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='votingparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='votingparticipation',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting', verbose_name='Голосование'),
        ),
    ]
