# Generated by Django 5.2.10 on 2026-05-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_historicalnomination_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnomination',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Nomination', 'verbose_name_plural': 'historical Номинации'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name': 'Nomination', 'verbose_name_plural': 'Номинации'},
        ),
        migrations.AlterField(
            model_name='votingparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='votingparticipation',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='voting.voting', verbose_name='Голосование'),
        ),
    ]
