# Generated by Django 5.2.10 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_historicalnomination_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoting',
            name='voting_type',
            field=models.CharField(choices=[('public', 'Публичное'), ('invite_only', 'По ссылке'), ('private', 'Закрытое (Черновик)')], default='public', max_length=15, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('public', 'Публичное'), ('invite_only', 'По ссылке'), ('private', 'Закрытое (Черновик)')], default='public', max_length=15, verbose_name='Тип'),
        ),
    ]
