# Generated by Django 5.2.10 on 2026-05-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_alter_historicalvoting_voting_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDailyPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос дня')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (Отображается на главной)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Виджет: Быстрый опрос',
                'verbose_name_plural': 'Виджет 2: Быстрые опросы',
            },
        ),
        migrations.CreateModel(
            name='WidgetNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('is_important', models.BooleanField(default=False, verbose_name='Закрепленная/Важная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Виджет: Новость',
                'verbose_name_plural': 'Виджет 1: Новости и Объявления',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetDailyPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Вариант ответа')),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.widgetdailypoll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='WidgetTopVoting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Количество кликов по кнопкам')),
                ('voting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='voting.voting', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Виджет: Аналитика голосования',
                'verbose_name_plural': 'Виджет 3: Топ популярных голосований',
                'ordering': ['-views_count', '-clicks_count'],
            },
        ),
    ]
