# Generated by Django 5.2.10 on 2026-05-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_widgetdailypoll_widgetnews_widgetdailypolloption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnomination',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Номинация', 'verbose_name_plural': 'historical Номинации'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name': 'Номинация', 'verbose_name_plural': 'Номинации'},
        ),
    ]
