# Generated by Django 5.2.10 on 2026-05-19 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_alter_historicalnomination_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvoting',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Голосование', 'verbose_name_plural': 'historical Голоса'},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Голосование', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='votingparticipation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalvote',
            name='nomination',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voting.nomination', verbose_name='Номинация'),
        ),
        migrations.AddField(
            model_name='vote',
            name='nomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.nomination', verbose_name='Номинация'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(fields=('voting', 'title'), name='unique_nomination_title_per_voting'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'nomination'), name='unique_vote_per_nomination'),
        ),
        migrations.AddConstraint(
            model_name='votingparticipation',
            constraint=models.UniqueConstraint(fields=('user', 'voting'), name='unique_user_voting_participation'),
        ),
    ]
