# Generated by Django 5.2.10 on 2026-05-19 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_alter_historicalvoting_options_alter_voting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvoting',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Голосование', 'verbose_name_plural': 'historical Голосования'},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосования'},
        ),
        migrations.RemoveConstraint(
            model_name='nomination',
            name='unique_nomination_title_per_voting',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_nomination',
        ),
        migrations.RemoveConstraint(
            model_name='votingparticipation',
            name='unique_user_voting_participation',
        ),
        migrations.RemoveField(
            model_name='historicalvote',
            name='nomination',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('voting', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='votingparticipation',
            unique_together={('user', 'voting')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nomination',
        ),
    ]
